In [1]:
import pandas as pd
import numpy as np
from numpy.random import randn

In [2]:
my_data = randn(4,3) # rows, columns
my_rows = ["A","B","C","D"]
my_cols = ["Monday","Tuesday","Friday",]

In [3]:
#Create DataFrame
my_df = pd.DataFrame(my_data, my_rows, my_cols)
my_df

     Monday   Tuesday    Friday
A -0.074083  0.611568  1.605610
B -0.699097  0.154574  0.150330
C  0.983450  0.473952  1.130162
D -1.187998  0.914584 -0.901318

In [4]:
#import csv file
my_df2 = pd.read_csv('entreprise.csv')

In [5]:
my_df2

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
55615,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55616,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55617,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55618,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55619,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [6]:
my_df2.loc[0] # loc means  location

Year                                                                        2024
Industry_aggregation_NZSIOC                                              Level 1
Industry_code_NZSIOC                                                       99999
Industry_name_NZSIOC                                              All industries
Units                                                         Dollars (millions)
Variable_code                                                                H01
Variable_name                                                       Total income
Variable_category                                          Financial performance
Value                                                                     979594
Industry_code_ANZSIC06         ANZSIC06 divisions A-S (excluding classes K633...
Name: 0, dtype: object

In [7]:
my_df2.loc[0:4]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...

In [8]:
my_df2.loc[[1,2,3,4,5]]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...
5,2024,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,71493,ANZSIC06 divisions A-S (excluding classes K633...

In [9]:
my_df2.loc[0]

Year                                                                        2024
Industry_aggregation_NZSIOC                                              Level 1
Industry_code_NZSIOC                                                       99999
Industry_name_NZSIOC                                              All industries
Units                                                         Dollars (millions)
Variable_code                                                                H01
Variable_name                                                       Total income
Variable_category                                          Financial performance
Value                                                                     979594
Industry_code_ANZSIC06         ANZSIC06 divisions A-S (excluding classes K633...
Name: 0, dtype: object

In [10]:
my_df2.loc[0:4]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...

In [11]:
my_df2.head() # grab first 5 rows from the file

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...

In [12]:
my_df2.tail() # grab last 5 rows from the file

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
55615,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55616,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55617,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55618,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55619,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [13]:
#get Column datatypes
my_df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 55620 entries, 0 to 55619
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         55620 non-null  int64
 1   Industry_aggregation_NZSIOC  55620 non-null  str
 2   Industry_code_NZSIOC         55620 non-null  str
 3   Industry_name_NZSIOC         55620 non-null  str
 4   Units                        55620 non-null  str
 5   Variable_code                55620 non-null  str
 6   Variable_name                55620 non-null  str
 7   Variable_category            55620 non-null  str
 8   Value                        55620 non-null  str
 9   Industry_code_ANZSIC06       55620 non-null  str
dtypes: int64(1), str(9)
memory usage: 4.2 MB

In [14]:
#get shape of Rows and Columns
my_df2.shape

(55620, 10)

In [15]:
#Get the Dimension of Data
my_df2.ndim

2

In [16]:
#Get some statistics about the Data
my_df2.describe()

               Year
count  55620.000000
mean    2018.500000
std        3.452084
min     2013.000000
25%     2015.750000
50%     2018.500000
75%     2021.250000
max     2024.000000

In [17]:
# Describe A specific Column 
my_df2['Year'].describe()

count    55620.000000
mean      2018.500000
std          3.452084
min       2013.000000
25%       2015.750000
50%       2018.500000
75%       2021.250000
max       2024.000000
Name: Year, dtype: float64

In [18]:
#select specific column using Brackets
my_df2['Year']

0        2024
1        2024
2        2024
3        2024
4        2024
         ...
55615    2013
55616    2013
55617    2013
55618    2013
55619    2013
Name: Year, Length: 55620, dtype: int64

In [19]:
#select specific column using Dot Notation
my_df2.Year

0        2024
1        2024
2        2024
3        2024
4        2024
         ...
55615    2013
55616    2013
55617    2013
55618    2013
55619    2013
Name: Year, Length: 55620, dtype: int64

In [20]:
#select specific column using location
my_df2.iloc[:,0]

0        2024
1        2024
2        2024
3        2024
4        2024
         ...
55615    2013
55616    2013
55617    2013
55618    2013
55619    2013
Name: Year, Length: 55620, dtype: int64

In [23]:
# Importing Dog CSV file - 
my_df3 = pd.read_csv('dog_data.csv')

In [24]:
my_df3

                    Breed              Color        DogName  OwnerZip
0                COCKAPOO              BROWN        CHARLEY     15236
1            GER SHEPHERD        BLACK/BROWN         TACODA     15238
2           BELG MALINOIS            BRINDLE           EICH     15238
3                   MIXED        BLACK/BROWN          ARROW     15104
4     AM PIT BULL TERRIER        WHITE/BROWN         OAKLEY     15139
...                   ...                ...            ...       ...
2665         GOLDENDOODLE              BROWN        WINSLOW     15044
2666    YORKSHIRE TERRIER        BLACK/BROWN  ROCKY KALAKOS     15220
2667              LAB MIX  WHITE/BLACK/BROWN          ELLIE     15220
2668         GOLDENDOODLE              WHITE       CLARENCE     15143
2669    SHETLAND SHEEPDOG              BLACK        GRIFFIN     15136

[2670 rows x 4 columns]

In [26]:
#count Disctinct Values - Decending 
my_df3['Color'].value_counts()

Color
BLACK                   371
BROWN                   309
WHITE                   226
WHITE/BLACK             196
BLACK/BROWN             183
                       ...
BROWN/ORANGE              1
BLACK/ORANGE/BRINDLE      1
BROWN/FAWN                1
BLACK/BROWN/GREY          1
BROWN/LIVER               1
Name: count, Length: 72, dtype: int64

In [27]:
#count Disctinct Values - Ascending 
my_df3['Color'].value_counts(ascending =True)

Color
BROWN/ORANGE              1
BLACK/ORANGE/BRINDLE      1
BROWN/FAWN                1
BLACK/BROWN/GREY          1
BROWN/LIVER               1
                       ...
BLACK/BROWN             183
WHITE/BLACK             196
WHITE                   226
BROWN                   309
BLACK                   371
Name: count, Length: 72, dtype: int64

In [28]:
#Dog Name - Without Nan
my_df3['DogName'].value_counts()

DogName
LUCY             35
BELLA            30
BAILEY           29
BUDDY            29
DAISY            26
                 ..
NINO              1
WINSLOW           1
ROCKY KALAKOS     1
CLARENCE          1
GRIFFIN           1
Name: count, Length: 1428, dtype: int64

In [32]:
#Dog Name - Nan
my_df3['DogName'].value_counts(dropna=False)

DogName
LUCY             35
BELLA            30
BAILEY           29
BUDDY            29
DAISY            26
                 ..
NINO              1
WINSLOW           1
ROCKY KALAKOS     1
CLARENCE          1
GRIFFIN           1
Name: count, Length: 1429, dtype: int64

In [44]:
# Get Relatice Frequency - Percentage
print(my_df3['Color'].value_counts(normalize=True))

Color
BLACK                   0.139212
BROWN                   0.115947
WHITE                   0.084803
WHITE/BLACK             0.073546
BLACK/BROWN             0.068668
                          ...
BROWN/ORANGE            0.000375
BLACK/ORANGE/BRINDLE    0.000375
BROWN/FAWN              0.000375
BLACK/BROWN/GREY        0.000375
BROWN/LIVER             0.000375
Name: proportion, Length: 72, dtype: float64

In [39]:
#Get Specific Item Count 
print(my_df3['Color'].value_counts()['WHITE'])

226